local M = {}

local function style(spec, extra)
  return vim.tbl_extend("force", spec or {}, extra or {})
end

function M.get(colors, opts)
  local transparent_bg = opts.transparent and colors.none or colors.bg
  local transparent_bg_dark = opts.transparent and colors.none or colors.bg_dark

  local highlights = {
    ColorColumn = { bg = colors.bg_highlight },
    Conceal = { fg = colors.fg_dark },
    CurSearch = { fg = colors.black, bg = colors.accent },
    Cursor = { fg = colors.bg, bg = colors.cursor },
    lCursor = { fg = colors.bg, bg = colors.cursor },
    CursorColumn = { bg = colors.bg_highlight },
    CursorIM = { fg = colors.bg, bg = colors.cursor },
    CursorLine = { bg = colors.bg_highlight },
    CursorLineNr = { fg = colors.accent, bold = true },
    Directory = { fg = colors.accent },
    DiffAdd = { bg = "#2c3827", fg = colors.green_bright },
    DiffChange = { bg = "#223743", fg = colors.accent_2 },
    DiffDelete = { bg = "#40272d", fg = colors.red },
    DiffText = { bg = "#35515d", fg = colors.blue_bright },
    EndOfBuffer = { fg = colors.bg },
    ErrorMsg = { fg = colors.error },
    FloatBorder = { fg = colors.border, bg = transparent_bg_dark },
    FloatTitle = { fg = colors.accent, bg = transparent_bg_dark, bold = true },
    FoldColumn = { fg = colors.fg_gutter, bg = transparent_bg },
    Folded = { fg = colors.fg_dark, bg = colors.bg_dark },
    IncSearch = { fg = colors.black, bg = colors.yellow },
    LineNr = { fg = colors.fg_gutter },
    MatchParen = { fg = colors.yellow, bold = true },
    ModeMsg = { fg = colors.accent, bold = true },
    MoreMsg = { fg = colors.accent },
    NonText = { fg = colors.fg_gutter },
    Normal = { fg = colors.fg, bg = transparent_bg },
    NormalFloat = { fg = colors.fg, bg = transparent_bg_dark },
    NormalNC = { fg = colors.fg, bg = transparent_bg },
    Pmenu = { fg = colors.fg, bg = transparent_bg_dark },
    PmenuSbar = { bg = colors.bg_highlight },
    PmenuSel = { fg = colors.accent, bg = colors.bg_highlight },
    PmenuThumb = { bg = colors.accent },
    Question = { fg = colors.accent },
    QuickFixLine = { bg = colors.bg_highlight, bold = true },
    Search = { fg = colors.fg, bg = colors.bg_search },
    SignColumn = { fg = colors.fg_gutter, bg = transparent_bg },
    SpecialKey = { fg = colors.accent_2 },
    SpellBad = { sp = colors.error, undercurl = true },
    SpellCap = { sp = colors.info, undercurl = true },
    SpellLocal = { sp = colors.hint, undercurl = true },
    SpellRare = { sp = colors.purple, undercurl = true },
    StatusLine = { fg = colors.fg_dark, bg = colors.bg_dark },
    StatusLineNC = { fg = colors.fg_gutter, bg = colors.bg_dark },
    Substitute = { fg = colors.black, bg = colors.orange },
    TabLine = { fg = colors.fg_dark, bg = colors.bg_dark },
    TabLineFill = { bg = colors.bg_dark },
    TabLineSel = { fg = colors.accent, bg = colors.bg, bold = true },
    Title = { fg = colors.accent, bold = true },
    VertSplit = { fg = colors.border },
    Visual = { bg = colors.selection },
    WarningMsg = { fg = colors.warning },
    Whitespace = { fg = colors.fg_gutter },
    WildMenu = { fg = colors.black, bg = colors.accent },
    WinBar = { fg = colors.fg_dark, bg = transparent_bg },
    WinBarNC = { fg = colors.fg_gutter, bg = transparent_bg },
    WinSeparator = { fg = colors.border },

    Comment = style({ fg = colors.fg_comment }, opts.styles.comments),
    Constant = { fg = colors.red },
    String = style({ fg = colors.green }, opts.styles.strings),
    Character = { fg = colors.green },
    Number = { fg = colors.red },
    Boolean = { fg = colors.red },
    Float = { fg = colors.red },
    Identifier = style({ fg = colors.fg }, opts.styles.variables),
    Function = style({ fg = colors.blue_dark }, opts.styles.functions),
    Statement = style({ fg = colors.red }, opts.styles.keywords),
    Conditional = style({ fg = colors.red }, opts.styles.keywords),
    Repeat = style({ fg = colors.red }, opts.styles.keywords),
    Label = { fg = colors.orange },
    Operator = { fg = colors.accent_2 },
    Keyword = style({ fg = colors.red }, opts.styles.keywords),
    Exception = style({ fg = colors.red }, opts.styles.keywords),
    PreProc = { fg = colors.orange },
    Include = { fg = colors.yellow },
    Define = { fg = colors.accent_2 },
    Macro = { fg = colors.blue_dark },
    PreCondit = { fg = colors.red },
    Type = { fg = colors.yellow },
    StorageClass = { fg = colors.purple },
    Structure = { fg = colors.yellow },
    Typedef = { fg = colors.yellow },
    Special = { fg = colors.accent_2 },
    SpecialChar = { fg = colors.accent_2 },
    Tag = { fg = colors.red },
    Delimiter = { fg = colors.blue_bright },
    SpecialComment = style({ fg = colors.fg_comment_soft, italic = true }, opts.styles.comments),
    Debug = { fg = colors.red },
    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Ignore = { fg = colors.fg_gutter },
    Error = { fg = colors.error },
    Todo = { fg = colors.black, bg = colors.yellow, bold = true },

    DiagnosticError = { fg = colors.error },
    DiagnosticWarn = { fg = colors.warning },
    DiagnosticInfo = { fg = colors.info },
    DiagnosticHint = { fg = colors.hint },
    DiagnosticOk = { fg = colors.green_bright },
    DiagnosticUnderlineError = { undercurl = true, sp = colors.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = colors.warning },
    DiagnosticUnderlineInfo = { undercurl = true, sp = colors.info },
    DiagnosticUnderlineHint = { undercurl = true, sp = colors.hint },
    DiagnosticVirtualTextError = { fg = colors.error, bg = "#3b252a" },
    DiagnosticVirtualTextWarn = { fg = colors.warning, bg = "#3c3526" },
    DiagnosticVirtualTextInfo = { fg = colors.info, bg = "#233842" },
    DiagnosticVirtualTextHint = { fg = colors.hint, bg = "#243534" },
    DiagnosticFloatingError = { fg = colors.error },
    DiagnosticFloatingWarn = { fg = colors.warning },
    DiagnosticFloatingInfo = { fg = colors.info },
    DiagnosticFloatingHint = { fg = colors.hint },
    DiagnosticSignError = { fg = colors.error },
    DiagnosticSignWarn = { fg = colors.warning },
    DiagnosticSignInfo = { fg = colors.info },
    DiagnosticSignHint = { fg = colors.hint },

    GitSignsAdd = { fg = colors.green_bright },
    GitSignsChange = { fg = colors.accent_2 },
    GitSignsDelete = { fg = colors.red },

    DiffAdded = { fg = colors.green_bright },
    DiffRemoved = { fg = colors.red },
    DiffChanged = { fg = colors.accent_2 },
    diffAdded = { fg = colors.green_bright },
    diffRemoved = { fg = colors.red },
    diffChanged = { fg = colors.accent_2 },
    diffFile = { fg = colors.blue_dark },
    diffNewFile = { fg = colors.green_bright },
    diffOldFile = { fg = colors.yellow },
    diffLine = { fg = colors.fg_dark },
    diffIndexLine = { fg = colors.purple },

    ["@annotation"] = { fg = colors.yellow },
    ["@attribute"] = { fg = colors.purple },
    ["@boolean"] = { fg = colors.red },
    ["@character"] = { fg = colors.green },
    ["@character.special"] = { fg = colors.accent_2 },
    ["@comment"] = style({ fg = colors.fg_comment }, opts.styles.comments),
    ["@comment.documentation"] = style({ fg = colors.fg_comment_soft, italic = true }, opts.styles.comments),
    ["@comment.todo"] = { fg = colors.black, bg = colors.yellow, bold = true },
    ["@comment.note"] = { fg = colors.black, bg = colors.info, bold = true },
    ["@comment.warning"] = { fg = colors.black, bg = colors.warning, bold = true },
    ["@comment.error"] = { fg = colors.white, bg = colors.error, bold = true },
    ["@conditional"] = style({ fg = colors.red }, opts.styles.keywords),
    ["@constant"] = { fg = colors.white },
    ["@constant.builtin"] = { fg = colors.yellow, italic = true },
    ["@constant.macro"] = { fg = colors.blue_dark },
    ["@constructor"] = { fg = colors.yellow },
    ["@diff.delta"] = { fg = colors.accent_2 },
    ["@diff.minus"] = { fg = colors.red },
    ["@diff.plus"] = { fg = colors.green_bright },
    ["@exception"] = style({ fg = colors.red }, opts.styles.keywords),
    ["@field"] = { fg = colors.red },
    ["@float"] = { fg = colors.red },
    ["@function"] = style({ fg = colors.blue_dark }, opts.styles.functions),
    ["@function.builtin"] = { fg = colors.purple },
    ["@function.call"] = { fg = colors.blue_dark },
    ["@function.macro"] = { fg = colors.blue_dark },
    ["@include"] = { fg = colors.yellow },
    ["@keyword"] = style({ fg = colors.red }, opts.styles.keywords),
    ["@keyword.function"] = style({ fg = colors.red }, opts.styles.keywords),
    ["@keyword.operator"] = { fg = colors.red },
    ["@keyword.return"] = style({ fg = colors.red }, opts.styles.keywords),
    ["@label"] = { fg = colors.orange },
    ["@markup.heading"] = { fg = colors.accent_2, bold = true },
    ["@markup.italic"] = { fg = colors.red, italic = true },
    ["@markup.link"] = { fg = colors.red, underline = true },
    ["@markup.link.label"] = { fg = colors.accent_2 },
    ["@markup.link.url"] = { fg = colors.green, underline = true },
    ["@markup.list"] = { fg = colors.accent_2 },
    ["@markup.quote"] = { fg = colors.accent_2, italic = true },
    ["@markup.raw"] = { fg = colors.green },
    ["@markup.strong"] = { fg = colors.red, bold = true },
    ["@method"] = { fg = colors.red },
    ["@method.call"] = { fg = colors.red },
    ["@module"] = { fg = colors.yellow },
    ["@namespace"] = { fg = colors.yellow },
    ["@number"] = { fg = colors.orange },
    ["@operator"] = { fg = colors.accent_2 },
    ["@parameter"] = style({ fg = colors.fg, italic = true }, opts.styles.variables),
    ["@parameter.reference"] = { fg = colors.red, italic = true },
    ["@property"] = { fg = colors.red },
    ["@punctuation.bracket"] = { fg = colors.blue_dark },
    ["@punctuation.delimiter"] = { fg = colors.blue_bright },
    ["@punctuation.special"] = { fg = colors.blue_bright },
    ["@repeat"] = style({ fg = colors.red }, opts.styles.keywords),
    ["@storageclass"] = { fg = colors.purple },
    ["@string"] = style({ fg = colors.green }, opts.styles.strings),
    ["@string.escape"] = { fg = colors.fg },
    ["@string.regex"] = { fg = colors.cyan },
    ["@string.special"] = { fg = colors.orange },
    ["@tag"] = { fg = colors.red },
    ["@tag.attribute"] = { fg = colors.purple },
    ["@tag.delimiter"] = { fg = colors.accent_2 },
    ["@text"] = { fg = colors.fg },
    ["@text.literal"] = { fg = colors.green },
    ["@text.reference"] = { fg = colors.red },
    ["@title"] = { fg = colors.accent_2, bold = true },
    ["@type"] = { fg = colors.yellow },
    ["@type.builtin"] = { fg = colors.accent_2 },
    ["@variable"] = style({ fg = colors.fg }, opts.styles.variables),
    ["@variable.builtin"] = { fg = colors.accent_2 },
    ["@variable.member"] = { fg = colors.red },

    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@property" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@type" },
    ["@lsp.type.macro"] = { link = "@function.macro" },
    ["@lsp.type.method"] = { link = "@method" },
    ["@lsp.type.namespace"] = { link = "@namespace" },
    ["@lsp.type.parameter"] = { link = "@parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type" },
    ["@lsp.type.variable"] = { link = "@variable" },
-- rust
    ["@lsp.type.method.rust"] = { link = "@function.call" },
    ["@lsp.type.namespace.rust"] = { link = "@module" },
    ["@lsp.type.mod.rust"] = { link = "@module" },
    ["@lsp.typemod.namespace.crateRoot.rust"] = { link = "@module" },
    ["@lsp.type.enumMember.rust"] = { link = "@type" },


    TelescopeNormal = { fg = colors.fg, bg = transparent_bg_dark },
    TelescopeBorder = { fg = colors.border, bg = transparent_bg_dark },
    TelescopeTitle = { fg = colors.accent, bold = true },
    TelescopePromptTitle = { fg = colors.black, bg = colors.accent, bold = true },
    TelescopePreviewTitle = { fg = colors.black, bg = colors.blue_dark, bold = true },
    TelescopeResultsTitle = { fg = colors.black, bg = colors.yellow, bold = true },
    TelescopePromptNormal = { fg = colors.accent, bg = transparent_bg },
    TelescopePromptBorder = { fg = colors.accent, bg = transparent_bg },
    TelescopeSelection = { fg = colors.accent, bg = colors.bg_highlight },
    TelescopeMatching = { fg = colors.yellow, bold = true },

    NeoTreeNormal = { fg = colors.fg, bg = transparent_bg_dark },
    NeoTreeNormalNC = { fg = colors.fg, bg = transparent_bg_dark },
    NeoTreeFloatBorder = { fg = colors.border, bg = transparent_bg_dark },
    NeoTreeTitleBar = { fg = colors.black, bg = colors.accent, bold = true },
    NeoTreeDirectoryName = { fg = colors.fg },
    NeoTreeDirectoryIcon = { fg = colors.accent_2 },
    NeoTreeRootName = { fg = colors.accent, bold = true },
    NeoTreeFileNameOpened = { fg = colors.accent },
    NeoTreeIndentMarker = { fg = colors.fg_gutter },
    NeoTreeGitAdded = { fg = colors.green_bright },
    NeoTreeGitModified = { fg = colors.warning },
    NeoTreeGitDeleted = { fg = colors.red },

    CmpDocumentation = { fg = colors.fg, bg = transparent_bg_dark },
    CmpDocumentationBorder = { fg = colors.border, bg = transparent_bg_dark },
    CmpItemAbbr = { fg = colors.fg },
    CmpItemAbbrDeprecated = { fg = colors.fg_dark, strikethrough = true },
    CmpItemAbbrMatch = { fg = colors.accent, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = colors.accent_2, bold = true },
    CmpItemKind = { fg = colors.blue_dark },
    CmpItemMenu = { fg = colors.fg_dark, italic = true },
    CmpItemKindFunction = { fg = colors.blue_dark },
    CmpItemKindMethod = { fg = colors.red },
    CmpItemKindVariable = { fg = colors.fg },
    CmpItemKindField = { fg = colors.red },
    CmpItemKindProperty = { fg = colors.red },
    CmpItemKindClass = { fg = colors.yellow },
    CmpItemKindInterface = { fg = colors.yellow },
    CmpItemKindModule = { fg = colors.purple },
    CmpItemKindKeyword = { fg = colors.accent_2 },
    CmpItemKindSnippet = { fg = colors.green },
    CmpItemKindText = { fg = colors.fg_dark },

    GitSignsAddLn = { bg = "#263426" },
    GitSignsChangeLn = { bg = "#21343d" },
    GitSignsDeleteLn = { bg = "#39252a" },
    GitSignsCurrentLineBlame = { fg = colors.fg_comment, italic = true },

    TroubleNormal = { fg = colors.fg, bg = transparent_bg_dark },
    TroubleNormalNC = { fg = colors.fg, bg = transparent_bg_dark },
    TroubleText = { fg = colors.fg },
    TroubleCount = { fg = colors.black, bg = colors.accent, bold = true },
    TroubleIconDirectory = { fg = colors.accent_2 },
    TroubleIconFile = { fg = colors.fg },
    TroublePreview = { fg = colors.accent, bold = true },

    FlashBackdrop = { fg = colors.fg_gutter },
    FlashLabel = { fg = colors.black, bg = colors.accent, bold = true },
    FlashMatch = { fg = colors.yellow, bg = colors.bg_highlight, bold = true },
    FlashCurrent = { fg = colors.black, bg = colors.orange, bold = true },
    FlashCursor = { fg = colors.black, bg = colors.red_bright, bold = true },
    FlashPrompt = { fg = colors.accent },

    OilDir = { fg = colors.accent_2 },
    OilFile = { fg = colors.fg },
    OilLink = { fg = colors.purple },
    OilSocket = { fg = colors.red },
    OilOrphanLink = { fg = colors.warning },
    OilChange = { fg = colors.accent_2 },
    OilCreate = { fg = colors.green_bright },
    OilDelete = { fg = colors.red },
    OilMove = { fg = colors.yellow },
    OilCopy = { fg = colors.blue_dark },
    OilPermissionRead = { fg = colors.green },
    OilPermissionWrite = { fg = colors.yellow },
    OilPermissionExecute = { fg = colors.red },

    WhichKey = { fg = colors.accent },
    WhichKeyGroup = { fg = colors.yellow },
    WhichKeyDesc = { fg = colors.blue_dark },
    WhichKeyIcon = { fg = colors.accent_2 },
    WhichKeyTitle = { fg = colors.accent, bold = true },
    WhichKeyValue = { fg = colors.fg_dark },
    WhichKeySeparator = { fg = colors.fg_dark },
    WhichKeyFloat = { bg = transparent_bg_dark },

    LazyNormal = { fg = colors.fg, bg = transparent_bg_dark },
    LazyButton = { fg = colors.fg, bg = colors.bg_highlight },
    LazyButtonActive = { fg = colors.black, bg = colors.accent, bold = true },
    LazyComment = { fg = colors.fg_comment, italic = true },
    LazyCommit = { fg = colors.blue_dark },
    LazyCommitIssue = { fg = colors.purple, underline = true },
    LazyDir = { fg = colors.accent_2 },
    LazyH1 = { fg = colors.black, bg = colors.accent, bold = true },
    LazyH2 = { fg = colors.yellow, bold = true },
    LazyProp = { fg = colors.fg_dark },
    LazyReasonPlugin = { fg = colors.purple },
    LazySpecial = { fg = colors.blue_bright },
    LazyValue = { fg = colors.orange },

    MasonNormal = { fg = colors.fg, bg = transparent_bg_dark },
    NotifyBackground = { bg = transparent_bg_dark },
    NotifyERRORBorder = { fg = colors.error, bg = transparent_bg_dark },
    NotifyWARNBorder = { fg = colors.warning, bg = transparent_bg_dark },
    NotifyINFOBorder = { fg = colors.info, bg = transparent_bg_dark },
    NotifyDEBUGBorder = { fg = colors.purple, bg = transparent_bg_dark },
    NotifyTRACEBorder = { fg = colors.accent_2, bg = transparent_bg_dark },
    NotifyERRORTitle = { fg = colors.error, bold = true },
    NotifyWARNTitle = { fg = colors.warning, bold = true },
    NotifyINFOTitle = { fg = colors.info, bold = true },
    NotifyDEBUGTitle = { fg = colors.purple, bold = true },
    NotifyTRACETitle = { fg = colors.accent_2, bold = true },
    NotifyERRORIcon = { fg = colors.error },
    NotifyWARNIcon = { fg = colors.warning },
    NotifyINFOIcon = { fg = colors.info },
    NotifyDEBUGIcon = { fg = colors.purple },
    NotifyTRACEIcon = { fg = colors.accent_2 },

    NoiceCmdline = { fg = colors.fg, bg = transparent_bg_dark },
    NoiceCmdlineIcon = { fg = colors.accent },
    NoiceCmdlinePopup = { fg = colors.fg, bg = transparent_bg_dark },
    NoiceCmdlinePopupBorder = { fg = colors.border, bg = transparent_bg_dark },
    NoiceConfirmBorder = { fg = colors.yellow, bg = transparent_bg_dark },
    NoiceMini = { fg = colors.fg_dark, bg = transparent_bg_dark },
    NoicePopup = { fg = colors.fg, bg = transparent_bg_dark },
    NoicePopupBorder = { fg = colors.border, bg = transparent_bg_dark },
    NoiceSplit = { fg = colors.fg, bg = transparent_bg_dark },
    NoiceVirtualText = { fg = colors.fg_comment, italic = true },
    NoiceLspProgressTitle = { fg = colors.accent, bold = true },
    NoiceLspProgressSpinner = { fg = colors.accent_2 },
    NoiceLspProgressClient = { fg = colors.fg_dark },

    MiniAnimateCursor = { reverse = true },
    MiniClueBorder = { fg = colors.border, bg = transparent_bg_dark },
    MiniClueDescGroup = { fg = colors.yellow },
    MiniClueDescSingle = { fg = colors.blue_dark },
    MiniClueNextKey = { fg = colors.accent },
    MiniClueNextKeyWithPostkeys = { fg = colors.accent_2 },
    MiniClueSeparator = { fg = colors.fg_dark },
    MiniCursorword = { bg = colors.bg_highlight },
    MiniCursorwordCurrent = { bg = colors.bg_highlight },
    MiniFilesBorder = { fg = colors.border, bg = transparent_bg_dark },
    MiniFilesCursorLine = { bg = colors.bg_highlight },
    MiniFilesDirectory = { fg = colors.accent_2 },
    MiniFilesFile = { fg = colors.fg },
    MiniHipatternsFixme = { fg = colors.white, bg = colors.error, bold = true },
    MiniHipatternsHack = { fg = colors.black, bg = colors.warning, bold = true },
    MiniHipatternsNote = { fg = colors.black, bg = colors.info, bold = true },
    MiniHipatternsTodo = { fg = colors.black, bg = colors.accent, bold = true },
    MiniIconsAzure = { fg = colors.blue_bright },
    MiniIconsBlue = { fg = colors.blue_dark },
    MiniIconsCyan = { fg = colors.cyan },
    MiniIconsGreen = { fg = colors.green_bright },
    MiniIconsGrey = { fg = colors.fg_dark },
    MiniIconsOrange = { fg = colors.orange },
    MiniIconsPurple = { fg = colors.purple },
    MiniIconsRed = { fg = colors.red },
    MiniIconsYellow = { fg = colors.yellow },
    MiniIndentscopeSymbol = { fg = colors.fg_gutter },
    MiniIndentscopePrefix = { nocombine = true },
    MiniJump = { fg = colors.black, bg = colors.accent, bold = true },
    MiniJump2dSpot = { fg = colors.black, bg = colors.yellow, bold = true },
    MiniNotifyBorder = { fg = colors.border, bg = transparent_bg_dark },
    MiniNotifyNormal = { fg = colors.fg, bg = transparent_bg_dark },
    MiniPickBorder = { fg = colors.border, bg = transparent_bg_dark },
    MiniPickBorderBusy = { fg = colors.warning, bg = transparent_bg_dark },
    MiniPickBorderText = { fg = colors.accent, bg = transparent_bg_dark },
    MiniPickHeader = { fg = colors.black, bg = colors.accent, bold = true },
    MiniPickIconDirectory = { fg = colors.accent_2 },
    MiniPickIconFile = { fg = colors.fg },
    MiniPickMatchCurrent = { bg = colors.bg_highlight },
    MiniPickMatchMarked = { fg = colors.yellow, bold = true },
    MiniPickMatchRanges = { fg = colors.accent, bold = true },
    MiniStatuslineDevinfo = { fg = colors.fg_dark, bg = colors.bg_dark },
    MiniStatuslineFileinfo = { fg = colors.fg_dark, bg = colors.bg_dark },
    MiniStatuslineFilename = { fg = colors.fg, bg = colors.bg_dark },
    MiniStatuslineInactive = { fg = colors.fg_gutter, bg = colors.bg_dark },
    MiniStatuslineModeCommand = { fg = colors.black, bg = colors.yellow, bold = true },
    MiniStatuslineModeInsert = { fg = colors.black, bg = colors.accent, bold = true },
    MiniStatuslineModeNormal = { fg = colors.black, bg = colors.blue_dark, bold = true },
    MiniStatuslineModeOther = { fg = colors.black, bg = colors.purple, bold = true },
    MiniStatuslineModeReplace = { fg = colors.black, bg = colors.red, bold = true },
    MiniStatuslineModeVisual = { fg = colors.black, bg = colors.orange, bold = true },
    MiniTablineCurrent = { fg = colors.accent, bg = colors.bg, bold = true },
    MiniTablineFill = { bg = colors.bg_dark },
    MiniTablineHidden = { fg = colors.fg_dark, bg = colors.bg_dark },
    MiniTablineModifiedCurrent = { fg = colors.yellow, bg = colors.bg, bold = true },
    MiniTablineModifiedHidden = { fg = colors.yellow, bg = colors.bg_dark },
    MiniTablineModifiedVisible = { fg = colors.yellow, bg = colors.bg_dark },
    MiniTablineTabpagesection = { fg = colors.black, bg = colors.accent },
    MiniTablineVisible = { fg = colors.fg, bg = colors.bg_dark },

    RainbowDelimiterRed = { fg = colors.magenta },
    RainbowDelimiterYellow = { fg = colors.yellow_bright },
    RainbowDelimiterBlue = { fg = colors.blue },
    RainbowDelimiterOrange = { fg = colors.orange },
    RainbowDelimiterGreen = { fg = colors.green },
    RainbowDelimiterViolet = { fg = colors.purple },
    RainbowDelimiterCyan = { fg = colors.cyan },

    IblIndent = { fg = colors.fg_gutter },
    IblWhitespace = { fg = colors.fg_gutter },
    IblScope = { fg = colors.accent_2 },
    IndentBlanklineChar = { fg = colors.fg_gutter },
    IndentBlanklineContextChar = { fg = colors.accent_2 },
    IndentBlanklineContextStart = { sp = colors.accent_2, underline = true },

    DashboardHeader = { fg = colors.accent_2 },
    DashboardCenter = { fg = colors.blue_dark },
    DashboardShortCut = { fg = colors.orange },
    DashboardFooter = { fg = colors.fg_comment, italic = true },
    DashboardKey = { fg = colors.yellow },
    DashboardDesc = { fg = colors.fg },
    DashboardIcon = { fg = colors.accent },

    AlphaHeader = { fg = colors.accent_2 },
    AlphaButtons = { fg = colors.blue_dark },
    AlphaShortcut = { fg = colors.orange },
    AlphaFooter = { fg = colors.fg_comment, italic = true },

    SnacksNormal = { fg = colors.fg, bg = transparent_bg_dark },
    SnacksBackdrop = { bg = colors.black, blend = 60 },
    SnacksBorder = { fg = colors.border, bg = transparent_bg_dark },
    SnacksTitle = { fg = colors.accent, bold = true },
    SnacksPicker = { fg = colors.fg, bg = transparent_bg_dark },
    SnacksPickerBorder = { fg = colors.border, bg = transparent_bg_dark },
    SnacksPickerTitle = { fg = colors.black, bg = colors.accent, bold = true },
    SnacksPickerDir = { fg = colors.fg_dark },
    SnacksPickerFile = { fg = colors.fg },
    SnacksPickerMatch = { fg = colors.yellow, bold = true },
    SnacksPickerPrompt = { fg = colors.accent },
    SnacksNotifierBorderError = { fg = colors.error, bg = transparent_bg_dark },
    SnacksNotifierBorderWarn = { fg = colors.warning, bg = transparent_bg_dark },
    SnacksNotifierBorderInfo = { fg = colors.info, bg = transparent_bg_dark },
    SnacksNotifierBorderDebug = { fg = colors.purple, bg = transparent_bg_dark },
    SnacksNotifierBorderTrace = { fg = colors.accent_2, bg = transparent_bg_dark },
    SnacksNotifierTitleError = { fg = colors.error, bold = true },
    SnacksNotifierTitleWarn = { fg = colors.warning, bold = true },
    SnacksNotifierTitleInfo = { fg = colors.info, bold = true },
    SnacksNotifierTitleDebug = { fg = colors.purple, bold = true },
    SnacksNotifierTitleTrace = { fg = colors.accent_2, bold = true },
    SnacksDashboardHeader = { fg = colors.accent_2 },
    SnacksDashboardDesc = { fg = colors.fg },
    SnacksDashboardFooter = { fg = colors.fg_comment, italic = true },
    SnacksDashboardIcon = { fg = colors.accent },
    SnacksDashboardKey = { fg = colors.yellow },
    SnacksIndent = { fg = colors.fg_gutter },
    SnacksIndentScope = { fg = colors.accent_2 },
  }

  highlights.FloatShadow = { bg = colors.black, blend = 60 }
  highlights.FloatShadowThrough = { bg = colors.black, blend = 80 }

  if type(opts.on_highlights) == "function" then
    opts.on_highlights(highlights, colors)
  end

  return vim.tbl_deep_extend("force", highlights, opts.highlights or {})
end

return M
